
export const AU_DESCRIPTIONS: Record<string, { name: string; desc: string }> = {
  "AU0":  { name: "Neutral face", desc: "Face em estado de repouso absoluto, caracterizando ausência de ativação." },
  "AU1":  { name: "Inner Brow Raiser", desc: "Elevação da parte interna das sobrancelhas, criando rugas horizontais no centro da testa (Frontalis, pars medialis)." },
  "AU2":  { name: "Outer Brow Raiser", desc: "Elevação da parte externa das sobrancelhas (Frontalis, pars lateralis)." },
  "AU4":  { name: "Brow Lowerer", desc: "Abaixamento das sobrancelhas gerando rugas verticais na glabela (Corrugator supercilii, Depressor supercilii, Procerus)." },
  "AU5":  { name: "Upper Lid Raiser", desc: "Elevação da pálpebra superior expõe a esclera (Levator palpebrae superioris)." },
  "AU6":  { name: "Cheek Raiser", desc: "Elevação das bochechas estreitando a fenda ocular — marcador do sorriso genuíno (Orbicularis oculi, pars orbitalis)." },
  "AU7":  { name: "Lid Tightener", desc: "Tensionamento das pálpebras (Orbicularis oculi, pars palpebralis)." },
  "AU8":  { name: "Lips Toward Each Other", desc: "Lábios movendo-se para fechamento (Orbicularis oris)." },
  "AU9":  { name: "Nose Wrinkler", desc: "Enrugamento da ponte do nariz, elevando as asas nasais (Levator labii superioris alaeque nasi)." },
  "AU10": { name: "Upper Lip Raiser", desc: "Elevação do lábio superior aprofundando o sulco nasolabial (Levator labii superioris)." },
  "AU11": { name: "Nasolabial Deepener", desc: "Aprofundamento do sulco nasolabial sem elevação pronunciada (Zygomaticus minor)." },
  "AU12": { name: "Lip Corner Puller", desc: "Tração dos cantos dos lábios para cima e para fora — movimento primário do sorriso (Zygomaticus major)." },
  "AU13": { name: "Cheek Puffer / Sharp Lip Puller", desc: "Tração dos cantos com inchaço das bochechas (Levator anguli oris / Caninus)." },
  "AU14": { name: "Dimpler", desc: "Tensionamento dos cantos da boca formando covinhas contra os dentes (Buccinator)." },
  "AU15": { name: "Lip Corner Depressor", desc: "Tração dos cantos da boca para baixo, arco invertido associado à tristeza (Depressor anguli oris / Triangularis)." },
  "AU16": { name: "Lower Lip Depressor", desc: "Depressão isolada do lábio inferior (Depressor labii inferioris)." },
  "AU17": { name: "Chin Raiser", desc: "Elevação da pele do queixo empurrando o lábio inferior para cima (Mentalis)." },
  "AU18": { name: "Lip Pucker", desc: "Projeção dos lábios para frente em formato de 'bico' (Incisivii labii superioris e inferioris)." },
  "AU19": { name: "Tongue Show", desc: "Exposição ou projeção da língua." },
  "AU20": { name: "Lip Stretcher", desc: "Estiramento horizontal dos lábios em direção às orelhas, comum no medo (Risorius, Platysma)." },
  "AU21": { name: "Neck Tightener", desc: "Tensionamento e visualização dos tendões do pescoço (Platysma)." },
  "AU22": { name: "Lip Funneler", desc: "Projeção dos lábios faneando-os em funil (Orbicularis oris)." },
  "AU23": { name: "Lip Tightener", desc: "Estreitamento e tensão das margens vermelhas dos lábios — sinal de contenção (Orbicularis oris)." },
  "AU24": { name: "Lip Pressor", desc: "Compressão mecânica de um lábio contra o outro — contenção emocional severa (Orbicularis oris)." },
  "AU25": { name: "Lips Part", desc: "Separação dos lábios por relaxamento muscular ou contração do Depressor labii inferioris." },
  "AU26": { name: "Jaw Drop", desc: "Queda relaxada da mandíbula inferior (relaxamento do Temporalis e Masseter)." },
  "AU27": { name: "Mouth Stretch", desc: "Abaixamento forçado da mandíbula abrindo a boca ao máximo (Pterigóideos, Digástrico)." },
  "AU28": { name: "Lip Suck", desc: "Sucção dos lábios para dentro sobre os dentes (Orbicularis oris)." },
  "AU29": { name: "Jaw Thrust", desc: "Impulso forçado da mandíbula para frente." },
  "AU30": { name: "Jaw Sideways", desc: "Deslocamento lateral da mandíbula." },
  "AU31": { name: "Jaw Clencher", desc: "Cerração ou aperto maxilar visível (Masseter)." },
  "AU32": { name: "Lip Bite", desc: "Morder o próprio lábio." },
  "AU33": { name: "Cheek Blow", desc: "Sopro inflando os tecidos ou expirando o ar." },
  "AU34": { name: "Cheek Puff", desc: "Inchar as bochechas com ar." },
  "AU35": { name: "Cheek Suck", desc: "Sugar as bochechas para dentro." },
  "AU36": { name: "Tongue Bulge", desc: "Língua gerando protuberância visível contra bochechas ou lábios." },
  "AU37": { name: "Lip Wipe", desc: "Comportamento de limpar os lábios." },
  "AU38": { name: "Nostril Dilator", desc: "Expansão das asas nasais para tomada profunda de ar (Nasalis, pars alaris)." },
  "AU39": { name: "Nostril Compressor", desc: "Compressão das asas nasais (Nasalis, pars transversa; Depressor septi nasi)." },
  "AU40": { name: "Sniff", desc: "Farejar ou respiração nasal curta e audível." },
  "AU41": { name: "Lid Droop", desc: "Queda passiva da pálpebra superior por relaxamento do Levator palpebrae superioris." },
  "AU42": { name: "Slit", desc: "Estreitamento ativo dos olhos até formar fendas (Orbicularis oculi)." },
  "AU43": { name: "Eyes Closed", desc: "Fechamento ocular por relaxamento do Levator palpebrae superioris." },
  "AU44": { name: "Squint", desc: "Olhar semicerrado combinando Corrugator supercilii e Orbicularis oculi." },
  "AU45": { name: "Blink", desc: "Piscar involuntário (relaxamento do Levator palpebrae + contração do Orbicularis oculi)." },
  "AU46": { name: "Wink", desc: "Piscadela intencional de um único olho (Orbicularis oculi)." },
  "AU50": { name: "Speech", desc: "Modificação estrutural gerada unicamente pelo ato de falar." },
  "AU80": { name: "Swallow", desc: "Engolir." },
  "AU81": { name: "Chewing", desc: "Mastigar." },
  "AU82": { name: "Shoulder Shrug", desc: "Dar de ombros." },
  "AU84": { name: "Head Shake", desc: "Balançar a cabeça em negação." },
  "AU85": { name: "Head Nod", desc: "Acenar a cabeça afirmativamente." },
  "AU91": { name: "Flash", desc: "Movimento rápido de pálpebras ou expressão súbita." },
  "AU92": { name: "Partial Flash", desc: "Flash parcial." },
  "AU97": { name: "Shiver / Tremble", desc: "Calafrios ou tremores." },
  "AU98": { name: "Fast Up-Down Look", desc: "Olhar rápido de cima a baixo." },
};

export const ZONE_CLINICAL_DESCRIPTIONS: Record<number, string> = {
  1: "Sobrecarga acústica indica padrões de evasão e desconfiança por percepção de ser subestimado. Autocrítica severa incapacitando o reconhecimento dos próprios talentos. Diretriz: conduzir para autovalidação, confiança na própria intuição e valorização da individualidade.",
  2: "Cérebro lógico operando em circuito repetitivo sem filtrar pensamentos improdutivos — precursor da depressão. Diretriz: romper ciclo de dúvidas para restaurar acesso ao hemisfério direito, criatividade e resolução de problemas.",
  3: "Queda de energia vocal; cognição focada em erros e perdas do passado. Esforço para solucionar conflitos insolúveis causa esgotamento. Diretriz: desligar do passado, estimular autoaceitação e ancoragem no presente para paz interior.",
  4: "Paciente excessivamente racional e distante; dificuldade em acessar sentimentos genuínos. Tensão fisiológica em garganta/respiração superior — medo de rejeição ou trauma. Diretriz: reverter embotamento e restaurar integração emocional para relacionamentos autênticos.",
  5: "Tensão por foco implacável em falhas e defeitos; incapacidade de autocompaixão. Diretriz: quebrar padrão guiando para perdão e aceitação plena, sem dependência de aprovação externa.",
  6: "Comportamentos baseados em julgamentos e punições; controle externo para suprir insegurança enraizada. Diretriz: desconstruir vínculos transacionais, estimular maturidade emocional e amor incondicional.",
  7: "Raiva disparada como defesa para esconder medo, perda ou traição. Tensão cardiovascular/muscular visível. Diretriz: diminuir reação defensiva perpétua, facilitar aceitação frente a mudanças e incertezas.",
  8: "Vitimização; sensação de que a vida 'acontece' passivamente por opressão de fracassos anteriores. Diretriz: transição da paralisia passiva para empoderamento, autonomia e responsabilização ativa.",
  9: "Vazamento de tensão mecânica na mandíbula/cordas vocais. Emoções ocultas para evitar conflitos, gerando isolamento. Diretriz: liberar bloqueio incentivando autoexpressão clara e fortalecimento de limites.",
  10: "Autossabotagem iminente; convicção subconsciente de indignidade a sucesso/amor/felicidade. Diretriz: eliminar culpa baseada em perfeição, ancorar aceitação total de limites e virtudes.",
  11: "Inflexibilidade cognitiva com regras mentais rígidas limitando perspectivas. Diretriz: dissolver estruturas dogmáticas para flexibilidade e exploração de novos cenários.",
  12: "Fragmentação sistêmica: desejos conscientes conflitam com crenças de que vitórias resultarão em dor/fracasso. Drenagem psíquica maciça e procrastinação. Diretriz: alinhar ação e emoção para clareza, integridade e continuidade.",
};

export function getAUDetails(codes: string[]): string[] {
  return codes.map(code => {
    const au = AU_DESCRIPTIONS[code];
    return au ? `${code}: ${au.name} — ${au.desc}` : `${code}: (código não mapeado)`;
  });
}
