"""Versioned, truthful legal notices presented by the FROID application.

Supplier PII is deployment configuration, never source-controlled.  Document
hashes include the rendered supplier identity so an acceptance proves the exact
text and party displayed to the user.
"""

from __future__ import annotations

import hashlib
import json
import os
from typing import Any


# Mudança material: a versão sobe e todo profissional volta a aceitar. Alterar
# limites clínicos sem subir a versão deixaria aceites antigos provando um
# texto que não é mais o vigente — exatamente o que o hash existe para impedir.
LEGAL_DOCUMENT_VERSION = "2026-08-25.br-pf-v4"


def _supplier() -> dict[str, str | bool]:
    supplier = {
        "name": os.getenv("FROID_LEGAL_SUPPLIER_NAME", "").strip(),
        "tax_id": os.getenv("FROID_LEGAL_SUPPLIER_TAX_ID", "").strip(),
        "address": os.getenv("FROID_LEGAL_SUPPLIER_ADDRESS", "").strip(),
        "contact_email": os.getenv("FROID_LEGAL_CONTACT_EMAIL", "").strip(),
        "privacy_email": os.getenv("FROID_LEGAL_PRIVACY_EMAIL", "").strip(),
    }
    supplier["configured"] = all(supplier.values())
    return supplier


COMMON_LIMITS = (
    "O FROID oferece indicadores, transcrições e conteúdo de inteligência artificial "
    "como apoio à atividade de profissional habilitado. Não realiza diagnóstico autônomo, "
    "não prescreve tratamento, não substitui avaliação clínica e não deve ser o único "
    "fundamento de decisão clínica, jurídica, laboral, securitária ou emergencial. "
    "Os indicadores do FROID são medidas de sinal acústico e visual, lidas contra a "
    "linha de base do próprio paciente. Não constituem teste psicológico, não são "
    "instrumento psicométrico validado, não produzem escore normativo comparável a "
    "outras pessoas e não inferem, por si, estado mental, quadro clínico ou construto "
    "psicológico."
)


# A fronteira entre medir e interpretar, dita ao profissional no momento em que
# ele assina — e não escondida numa nota técnica que ele nunca vai ler.
#
# Duas coisas distintas moram nesta cláusula, e ambas são condição do acesso:
# a interpretação é dele (o que mantém o FROID como instrumentação e não como
# instrumento de avaliação psicológica), e o material aprofundado que ele
# recebe é confidencial (o que preserva o capital intelectual sem precisar
# sonegar ao clínico o que ele precisa para confiar na medida).
INTERPRETATION_BOUNDARY = (
    "O FROID entrega medida; a interpretação é do profissional. O licenciado reconhece "
    "que os índices, marcadores e gráficos do FROID descrevem propriedades medidas da voz "
    "e da expressão facial em relação à linha de base do próprio paciente, e que a "
    "atribuição de significado clínico a essas medidas é ato privativo seu, praticado sob "
    "sua responsabilidade técnica e seu registro profissional. O licenciado se obriga a "
    "não apresentar, transcrever ou citar saída do FROID como resultado de teste "
    "psicológico, laudo, parecer, triagem diagnóstica ou conclusão sobre estado mental, "
    "em prontuário, documento, perícia ou comunicação a terceiros. Documentação técnica "
    "aprofundada eventualmente disponibilizada ao licenciado — incluindo parâmetros, "
    "critérios de composição, limiares e resultados de validação — é confidencial, "
    "destina-se exclusivamente ao uso próprio do licenciado e não pode ser reproduzida, "
    "publicada ou transferida a terceiros sem autorização escrita, obrigação que subsiste "
    "ao término deste contrato."
)


# O objeto de cada serviço, dito no contrato dele.
#
# Os dois produtos do FROID tratam de coisas incompatíveis, e um contrato que não
# diz qual dos dois está sendo contratado deixa a fronteira depender de quem lê.
# O FROID Psique olha para UMA PESSOA, com o consentimento dela e sob
# responsabilidade de um profissional habilitado. O FROID NR-1 olha para o
# TRABALHO, de forma anônima e agregada, e não pode chegar perto de pessoa
# nenhuma. Escrever isso no objeto é o que impede que a contratação de um seja
# usada para justificar o uso do outro.
OBJETO_PSIQUE = (
    "Este contrato tem por objeto a licença de uso do FROID Psique, ferramenta de "
    "apoio à escuta clínica destinada a profissional habilitado em saúde mental. "
    "A finalidade do serviço é ampliar a percepção do profissional durante e depois "
    "da sessão, por meio de instrumentação da fala e da expressão facial, "
    "transcrição, organização longitudinal do acompanhamento e conteúdo explicativo, "
    "sempre lidos contra a linha de base do próprio paciente. "
    "O objeto do FROID Psique é a pessoa atendida, com o conhecimento e as "
    "autorizações dela, e sob responsabilidade técnica de quem a atende. "
    "Este contrato NÃO abrange avaliação de riscos psicossociais do trabalho, "
    "avaliação de trabalhador a pedido de empregador, triagem admissional, "
    "exame de aptidão, nem qualquer uso cujo destinatário do resultado seja o "
    "empregador do avaliado. A avaliação de condições de trabalho é objeto de "
    "contrato próprio, o do FROID NR-1. "
    "Os dois serviços podem ser contratados pela mesma empresa e articulados "
    "entre si, e o FROID Psique pode ser o canal de apoio ao trabalhador que a "
    "campanha de avaliação exige — mas a articulação é de finalidade, nunca de "
    "dado: o vínculo clínico se estabelece entre o trabalhador e o profissional "
    "que o atende, por iniciativa do trabalhador, e nenhuma informação "
    "individual retorna ao empregador, inclusive a de quem procurou o canal."
)


# O objeto do serviço corporativo, e as duas frases que ele existe para sustentar:
# o objeto é a condição de trabalho, e a responsabilidade pelo GRO é da empresa.
#
# A segunda não é modéstia contratual: o Manual do GRO é explícito ("Mesmo com
# consultoria externa, a responsabilidade final pelo GRO é sempre da
# organização"), e um contrato que sugerisse o contrário venderia uma isenção que
# não existe — e que a fiscalização desmonta na primeira pergunta.
OBJETO_NR1 = (
    "Este contrato tem por objeto a prestação do serviço FROID NR-1: identificação "
    "de perigos e avaliação dos fatores de risco psicossociais relacionados ao "
    "trabalho, para integrar o Gerenciamento de Riscos Ocupacionais da contratante, "
    "nos termos do capítulo 1.5 da NR-1, na redação dada pela Portaria MTE nº "
    "1.419/2024, e das condições de trabalho previstas na NR-17. "
    "O objeto da avaliação é a CONDIÇÃO DE TRABALHO — a concepção, a organização e "
    "a gestão do trabalho —, nunca a pessoa do trabalhador. Não se verificam "
    "sintomas individuais, não se mede sinal biológico e não se avalia a saúde "
    "mental de quem quer que seja: verifica-se a que condições de trabalho o "
    "trabalhador está submetido. "
    "A responsabilidade pelo GRO, pelo PGR e por todas as suas etapas é da "
    "contratante, e não é transferida por este contrato. O FROID é o instrumento "
    "pelo qual a contratante executa parte desse processo; a decisão sobre medidas "
    "de prevenção, sua implementação e a assinatura dos documentos permanecem dela."
)


DOCUMENT_TEMPLATES: dict[str, dict[str, Any]] = {
    "privacy": {
        "title": "Política de Privacidade do FROID",
        "audiences": ["professional", "organization", "patient"],
        "sections": [
            ["Responsável pelo serviço", "{supplier_identity} é responsável pelas atividades próprias de cadastro, segurança, cobrança, suporte e operação do FROID. O profissional ou a clínica decide as finalidades clínicas e a composição do prontuário de seus pacientes. As funções de controlador e operador dependem de cada operação efetivamente realizada."],
            ["Dados tratados", "O serviço pode tratar cadastro, autenticação, agenda, pagamentos, registros de acesso e auditoria, voz, imagem, sinais faciais, métricas acústicas, transcrição, contexto da fala do paciente e do profissional, anotações, relatórios e histórico de sessões."],
            ["Como o processamento ocorre", "Parte das métricas é calculada no navegador. Em sessões remotas, áudio e vídeo são transmitidos pela internet e podem utilizar servidor TURN. Segmentos de áudio podem ser enviados ao backend e a provedor de transcrição. Transcrições, relatórios e registros autorizados podem ser armazenados na infraestrutura do FROID."],
            ["Fornecedores e transferência internacional", "O FROID pode utilizar infraestrutura de hospedagem na Estônia e fornecedores de pagamento, transcrição, inteligência artificial, e-mail e agenda. Isso pode envolver transferência internacional, protegida pelos mecanismos contratuais e técnicos aplicáveis."],
            ["Finalidades e bases", "Os dados são usados para executar o serviço contratado, proteger contas e sessões, processar pagamentos, atender obrigações legais, apoiar atividade de saúde por profissional habilitado e cumprir autorizações específicas. Pesquisa e Data-FROID exigem dados previamente aprovados pelo processo de anonimização e, quando aplicável, autorização opcional."],
            ["Retenção e eliminação", "A retenção considera finalidade, contrato, segurança e obrigações profissionais ou legais. Solicitações de eliminação serão analisadas e poderão resultar em exclusão, anonimização, bloqueio ou retenção restrita e fundamentada. Não se promete eliminação automática em prazo fixo quando existir obrigação legítima de guarda."],
            ["Direitos", "O titular pode solicitar confirmação, acesso, correção, informação sobre compartilhamentos, portabilidade quando aplicável, oposição, revogação de consentimento e anonimização, bloqueio ou eliminação nas hipóteses legais. Solicitações podem ser feitas pelo Portal do Paciente ou pelo contato de privacidade informado nesta página."],
            ["Segurança", "O FROID utiliza segregação por organização, controle de acesso, trilhas de auditoria, criptografia de registros clínicos e backups protegidos. Nenhum sistema elimina integralmente o risco; incidentes relevantes serão avaliados e comunicados conforme a legislação aplicável."],
        ],
    },
    "terms": {
        "title": "Termos Gerais de Uso do FROID",
        "audiences": ["professional", "organization", "patient"],
        "sections": [
            ["Objeto", "Estes termos regulam o acesso à plataforma FROID fornecida por {supplier_name}. O direito concedido é pessoal ou organizacional, limitado, não exclusivo, intransferível fora das permissões do plano e condicionado ao uso legítimo do serviço."],
            ["Limites clínicos", COMMON_LIMITS],
            ["Conduta e segurança", "O usuário deve proteger suas credenciais, manter dados corretos, respeitar permissões e comunicar suspeitas de acesso indevido. É vedado explorar vulnerabilidades, contornar controles, extrair dados em massa, copiar código ou tentar reconstruir algoritmos protegidos."],
            ["Disponibilidade", "A qualidade depende de navegador, dispositivo, microfone, câmera, rede e serviços externos. Manutenções, falhas e limitações podem ocorrer. Somente um SLA expressamente contratado cria garantia específica de disponibilidade ou tempo de resposta."],
            ["Propriedade intelectual", "Fábio de Assumpção Benhayon é o autor e titular do FROID. A contratação não transfere código, marca, textos, modelos, interfaces, pesos, fórmulas ou segredos comerciais. Permanecem assegurados os direitos legalmente reconhecidos ao usuário e a interoperabilidade permitida por lei."],
            ["Encerramento", "O acesso pode ser suspenso por violação de segurança, inadimplemento confirmado ou uso ilícito, preservados contraditório, direitos do titular, obrigações de guarda e meios de exportação aplicáveis."],
        ],
    },
    "professional_contract": {
        "title": "Contrato de Licença SaaS — FROID Psique, Profissional",
        "audiences": ["professional"],
        "sections": [
            ["Objeto e finalidade", OBJETO_PSIQUE],
            ["Partes e contratação", "O fornecedor é {supplier_identity}. O licenciado é o profissional identificado no cadastro. Pacote, quantidade de sessões, moeda e preço são os exibidos e confirmados na ordem eletrônica vinculada a este contrato."],
            ["Responsabilidade profissional", "O licenciado mantém responsabilidade técnica, ética e jurídica por atendimento, diagnóstico, documentos e conduta. Deve revisar transcrições, métricas, alertas e respostas de IA antes de utilizá-los no prontuário ou na tomada de decisão."],
            ["Natureza da medida e responsabilidade pela interpretação", INTERPRETATION_BOUNDARY],
            ["Pacientes e dados", "O profissional deve fornecer informação clara ao paciente, usar a plataforma dentro de sua habilitação e garantir base legal e autorizações adequadas. O FROID preservará a fala e o contexto registrados conforme as autorizações, a finalidade clínica e as regras de retenção aplicáveis."],
            ["Cobrança", "Cada compra corresponde à ordem apresentada antes do Stripe. A recarga automática somente existe quando escolhida separadamente; pode ser desativada para compras futuras, sem alterar recargas já processadas legitimamente."],
            ["Cancelamento e suporte", "Pedidos de cancelamento, cobrança e suporte serão tratados pelo contato informado. Reembolsos e direito de arrependimento observarão a legislação aplicável e a situação concreta da utilização do serviço."],
            ["Limites", COMMON_LIMITS],
        ],
    },
    "organization_contract": {
        "title": "Contrato de Licença SaaS — FROID Psique, Clínica ou Organização",
        "audiences": ["organization"],
        "sections": [
            ["Objeto e finalidade", OBJETO_PSIQUE],
            ["Partes e poderes", "O fornecedor é {supplier_identity}. A contratante é a pessoa jurídica identificada no cadastro, representada por pessoa que declara possuir poderes para contratar. As condições comerciais são as confirmadas na ordem eletrônica."],
            ["Governança", "A organização administra proprietários, administradores, supervisores, profissionais e auditores. Deve conceder acesso mínimo necessário, desligar usuários sem demora e definir formalmente responsabilidade técnica, custódia de prontuários e vínculo dos pacientes."],
            ["Dados e instruções", "A clínica define as finalidades clínicas e orienta o tratamento realizado em seu contexto. O FROID executa operações técnicas contratadas e atua como controlador apenas para finalidades próprias, como cadastro, segurança, faturamento, suporte e defesa de direitos."],
            ["Natureza da medida e responsabilidade pela interpretação", INTERPRETATION_BOUNDARY + " A contratante se obriga a vincular seus profissionais, colaboradores e prepostos a estas mesmas condições, respondendo por sua observância."],
            ["Isolamento e incidentes", "O FROID aplica segregação lógica, RLS, auditoria e controles de acesso. A clínica deve comunicar erros de permissão e cooperar na resposta a incidentes e solicitações de titulares."],
            ["Entrada, desligamento e exportação", "A organização responde pelo ciclo de vida de seus membros. O desligamento remove novos acessos sem apagar automaticamente prontuários sujeitos à custódia institucional, obrigações legais ou solicitações em análise."],
            ["Cobrança e limites", "Pacote, sessões, moeda, preço e recursos são os apresentados na ordem. Recarga automática é opcional. " + COMMON_LIMITS],
        ],
    },
    "patient_tcle": {
        "title": "TCLE — Uso do FROID pelo Paciente",
        "audiences": ["patient"],
        "sections": [
            ["O que é o FROID", "O FROID apoia o profissional por meio de métricas de voz, sinais faciais, transcrição e organização longitudinal. Seus resultados são estimativas sujeitas a ruído, contexto, iluminação, equipamento, idioma e qualidade da conexão."],
            ["O que acontece na sessão", "Conforme as autorizações escolhidas, a sessão pode transmitir e processar voz, vídeo, face, transcrição e conteúdo falado pelo paciente e pelo profissional. Parte do cálculo ocorre no navegador; outros dados podem trafegar e ser processados ou armazenados na infraestrutura e nos fornecedores descritos na Política de Privacidade."],
            ["Finalidade", "Os dados servem para apoiar o profissional responsável, produzir relatório, acompanhar evolução, proteger a sessão e manter registros autorizados. Pesquisa anonimizada e compartilhamento externo não são necessários para o atendimento e exigem escolha separada."],
            ["Escolha e revogação", "O paciente pode recusar autorizações opcionais e alterar autorizações futuras no Portal do Paciente. A recusa de processamento necessário pode impedir determinadas funcionalidades, sem retirar direitos sobre dados já tratados legitimamente ou registros cuja guarda seja obrigatória."],
            ["Limitações e emergência", COMMON_LIMITS + " O FROID não monitora continuamente crises e não substitui serviços de emergência. Em risco imediato, procure os serviços locais de urgência."],
            ["Direitos e contato", "O paciente pode consultar resultados, autorizações e solicitações no Portal do Paciente e contatar o profissional, a clínica ou o contato de privacidade do FROID."],
        ],
    },
}


DOCUMENT_TEMPLATES["research_tcle"] = {
    "title": "TCLE — Participação no Estudo de Validade dos Indicadores FROID",
    "audiences": ["patient"],
    "sections": [
        ["Convite e natureza da participação", "Você está sendo convidado a participar de um estudo que verifica se os indicadores do FROID guardam relação com questionários já validados na literatura, como o PHQ-9 e o GAD-7. Participar é opcional e é uma decisão separada do seu tratamento. Recusar não muda nada no seu atendimento, não altera o que o FROID faz na sua sessão e não é comunicado a ninguém além do registro desta recusa."],
        ["Por que este estudo existe", "Os indicadores do FROID descrevem propriedades medidas da voz e da expressão facial. Eles ainda não foram comparados formalmente com instrumentos validados. Enquanto essa comparação não existir, a resposta honesta sobre a validade deles é que ela ainda não foi estabelecida. Este estudo produz essa comparação."],
        ["O que acontece se você aceitar", "Em algumas sessões, o profissional aplicará um questionário breve, respondido por você, e registrará apenas a pontuação total. Essa pontuação será associada aos valores que o FROID mediu na mesma sessão. Não há procedimento adicional, exame, medicamento nem sessão extra. O questionário é aplicado e interpretado pelo profissional, não pelo FROID."],
        ["Que dados são usados e como", "São usados: a pontuação total do questionário, os valores dos indicadores daquela sessão e informações técnicas de qualidade da captação. A análise trabalha apenas com os pares de números, sem identificação. Não são usados o conteúdo da sua fala, a transcrição, a gravação nem o seu prontuário."],
        ["Riscos e benefícios", "O risco principal é o desconforto de responder perguntas sobre como você tem se sentido; você pode deixar qualquer pergunta em branco ou interromper. Não há benefício direto para você. O benefício esperado é coletivo: permitir que profissionais e pacientes saibam o que os indicadores do FROID de fato medem, ou que não medem o que se supunha."],
        ["Revogação", "Você pode retirar sua participação a qualquer momento, sem justificar e sem qualquer efeito sobre o atendimento. Ao pedir a retirada, os seus pares de dados são eliminados da base do estudo. Resultados já publicados a partir de análises anteriores não podem ser desfeitos, e por isso este documento informa isso antes e não depois."],
        ["Divulgação dos resultados", "Os resultados serão divulgados de forma agregada, sem qualquer identificação. Serão divulgados independentemente do que mostrarem, inclusive se contrariarem a hipótese do estudo. O tamanho da amostra e a direção esperada de cada relação foram definidos antes do início da coleta."],
        ["Responsável e contato", "O responsável pelo estudo é {supplier_identity}. Dúvidas sobre a pesquisa, sobre seus dados ou sobre a retirada da participação podem ser dirigidas a esse contato ou ao profissional que o atende."],
        ["Limites", COMMON_LIMITS],
    ],
}


DOCUMENT_TEMPLATES["nr1_company_contract"] = {
    "title": "Contrato de Prestação de Serviço — FROID NR-1, Riscos Psicossociais",
    "audiences": ["nr1_company"],
    "sections": [
        ["Partes e documentos integrantes", "O fornecedor é {supplier_identity}, doravante FORNECEDOR ou FROID. A contratante é a pessoa jurídica empregadora identificada pelo CNPJ no cadastro e na proposta comercial vinculada a este instrumento, representada por pessoa que declara possuir poderes suficientes para contratar. Integram este contrato, conforme aplicáveis: a proposta comercial aceita; o documento de critérios de gradação, classificação e tomada de decisão aplicável ao ciclo; a descrição metodológica e a identificação da versão do instrumento utilizada; o Anexo de Tratamento e Proteção de Dados, quando disponibilizado em documento apartado; e outros documentos técnicos ou comerciais expressamente incorporados. Em caso de divergência prevalece este contrato quanto às obrigações jurídicas gerais; a proposta comercial quanto a preço, prazo, quantidade de trabalhadores, estabelecimentos e escopo adicional; e os documentos metodológicos quanto aos critérios técnicos declarados, desde que não contrariem a legislação aplicável ou este instrumento."],
        ["Definições essenciais", "FROID NR-1 é o conjunto de funcionalidades, metodologia, instrumentos de coleta, processamento, análise, classificação, documentação e acompanhamento destinado a apoiar a contratante na identificação de perigos e avaliação dos fatores de risco psicossociais relacionados ao trabalho. Ciclo é o conjunto de atividades relativas a determinado período de avaliação, compreendendo preparação, coleta, processamento, análise, geração dos resultados e documentos contratados e, quando aplicável, acompanhamento. Unidade de avaliação é o recorte organizacional tecnicamente utilizado para análise e disponibilização de resultados, observado o estabelecimento, o setor, o grupo de trabalhadores e os pisos metodológicos aplicáveis. Fatores de risco psicossociais relacionados ao trabalho são os decorrentes ou relacionados à concepção, organização, conteúdo, gestão e condições em que o trabalho é realizado e que possam repercutir sobre a saúde e a segurança dos trabalhadores. AEP significa Avaliação Ergonômica Preliminar; AET, Análise Ergonômica do Trabalho; GRO, Gerenciamento de Riscos Ocupacionais; e PGR, Programa de Gerenciamento de Riscos."],
        ["Objeto", "Este contrato tem por objeto a prestação do serviço FROID NR-1, destinado a funcionar como instrumento técnico documentado de identificação de perigos, caracterização da exposição, avaliação e classificação dos fatores de risco psicossociais relacionados ao trabalho, integração às etapas pertinentes da Avaliação Ergonômica Preliminar e apoio à elaboração, atualização, execução e acompanhamento do PGR da contratante, nos termos da NR-1 e da NR-17 aplicáveis."],
        ["Objeto material da avaliação", "O objeto da avaliação são as condições de trabalho, especialmente aspectos relacionados à concepção, organização, conteúdo e gestão do trabalho, às exigências das atividades e às circunstâncias laborais às quais grupos de trabalhadores estejam submetidos. A avaliação não tem por objeto diagnosticar a personalidade, a saúde mental, o estado emocional ou qualquer condição clínica individual do trabalhador."],
        ["Natureza não clínica", "No escopo ordinário do FROID NR-1 não são realizados diagnóstico médico, psicológico ou psiquiátrico; não são realizados testes psicológicos destinados à avaliação individual de pessoa; não são medidos sinais biológicos; não são emitidos prontuários clínicos; não são atribuídos diagnósticos de saúde mental; não são produzidos rankings individuais de trabalhadores; e não é realizado juízo sobre aptidão ou inaptidão laboral individual. As perguntas e evidências utilizadas destinam-se a caracterizar condições, exigências, circunstâncias e fatores relacionados ao trabalho."],
        ["Instrumento dentro do GRO, e o que não se transfere", "O FROID constitui instrumento de apoio técnico à execução de etapas do GRO e do PGR, mas não transfere ao FORNECEDOR a responsabilidade legal da contratante pela implementação e manutenção do gerenciamento de riscos ocupacionais. A contratante permanece responsável pelas decisões empresariais e regulatórias relativas ao seu GRO, incluindo a aprovação das medidas de prevenção, sua implementação, alocação de recursos, integração com os demais riscos ocupacionais, assinatura dos documentos sob sua responsabilidade e cumprimento das demais obrigações legais que não estejam expressamente incluídas no escopo contratado."],
        ["Responsabilidade própria do fornecedor", "A permanência da responsabilidade regulatória da contratante não exclui nem reduz a responsabilidade do FORNECEDOR pela adequada execução das obrigações por ele assumidas, incluindo, conforme o escopo: funcionamento das funcionalidades fornecidas; integridade dos cálculos e processamentos realizados pelo sistema; aplicação dos critérios metodológicos declarados; geração dos documentos contratados a partir dos dados e parâmetros corretamente fornecidos; observância das obrigações de confidencialidade, segurança e proteção de dados sob sua responsabilidade; e correção de erro técnico imputável ao serviço. O FORNECEDOR não responderá por conclusões incorretas decorrentes de informação falsa, incompleta, desatualizada ou incorretamente cadastrada pela contratante, sem prejuízo do dever de informar inconsistências que sejam objetivamente detectáveis pelo sistema ou durante a prestação do serviço."],
        ["Princípios metodológicos e inexistência de metodologia única", "O FROID utilizará metodologia, ferramentas e técnicas compatíveis com os fatores de risco abrangidos pelo serviço, sendo a versão metodológica aplicável identificada e preservada para fins de rastreabilidade. As partes reconhecem que as Normas Regulamentadoras não estabelecem um único questionário, índice, taxa de resposta ou ferramenta obrigatória para avaliação dos fatores de risco psicossociais relacionados ao trabalho. A adequação do método deverá ser apreciada conforme a natureza da atividade, as características da organização, os fatores de risco avaliados, a suficiência das evidências disponíveis e as circunstâncias concretas do trabalho."],
        ["Questionário como fonte de evidência, e métodos complementares", "Quando utilizado questionário, suas respostas constituirão fonte estruturada de evidências para caracterização da exposição e avaliação das condições de trabalho. O questionário, isoladamente, não será apresentado como prova automática e universal de cumprimento integral do GRO, do PGR, da NR-1 ou da NR-17. Conforme a situação concreta, poderão ser necessários ou recomendáveis métodos adicionais, inclusive análise documental, entrevistas, grupos focais ou oficinas, observação da atividade, análise de processos e organização do trabalho, avaliação técnica de situações específicas, dados organizacionais pertinentes, informações legitimamente provenientes do PCMSO ou de outros processos de SST respeitados finalidade e necessidade, AET e outros métodos qualitativos, semiquantitativos, quantitativos ou combinados tecnicamente adequados. Salvo disposição expressa na proposta comercial, atividades complementares que excedam o escopo do FROID NR-1 dependerão de contratação específica ou de execução por profissional ou prestador competente indicado pela contratante."],
        ["Integração com a Avaliação Ergonômica Preliminar", "O FROID produzirá informações e evidências destinadas a integrar, quanto aos fatores de risco psicossociais relacionados ao trabalho abrangidos pelo serviço, as etapas pertinentes da Avaliação Ergonômica Preliminar, e poderá gerar registro técnico das evidências utilizadas, métodos aplicados, resultados e conclusões referentes ao escopo avaliado, de forma a subsidiar o registro da AEP pela contratante. A utilização do FROID para fatores psicossociais não implica, por si só, avaliação de todos os demais aspectos ergonômicos previstos na NR-17, incluindo aspectos físicos, biomecânicos, ambientais, mobiliários, equipamentos ou outras condições que não estejam expressamente incluídas no escopo contratado. A coleta realizada pelo FROID constitui um dos meios possíveis de participação e escuta dos trabalhadores; a contratante permanece responsável por assegurar mecanismos suficientes de participação, consulta e comunicação exigidos pelas normas aplicáveis, inclusive quando a adesão à coleta não produzir evidências suficientes para determinada unidade de avaliação."],
        ["Escalonamento e investigação adicional", "Sempre que as evidências obtidas forem insuficientes para uma conclusão tecnicamente segura, ou indicarem situação que demande aprofundamento, o resultado deverá registrar essa circunstância e, quando aplicável, indicar a necessidade de complementação metodológica ou avaliação técnica adicional. Sem prejuízo de outras situações tecnicamente justificadas, poderão constituir gatilho de aprofundamento: insuficiência quantitativa ou qualitativa de evidências; adesão insuficiente para formação de determinada unidade de avaliação; resultados contraditórios ou de difícil interpretação; heterogeneidade acentuada dentro de uma mesma unidade; identificação de risco classificado em nível que exija intervenção prioritária; evidências relevantes de exposição cuja natureza não possa ser suficientemente compreendida por questionário; ocorrência ou repetição de relatos de violência, assédio, sobrecarga ou exigências conflitantes; inadequação, insuficiência ou ineficácia aparente das medidas existentes; necessidade de avaliação mais aprofundada da atividade real; indicação proveniente do acompanhamento da saúde dos trabalhadores nos limites legalmente aplicáveis; acidente ou doença cuja análise indique possível relação com as condições de trabalho; modificações relevantes de tecnologias, processos, organização ou condições de trabalho; solicitação justificada de trabalhadores ou da CIPA; e qualquer hipótese em que a NR-17 determine ou torne necessária uma Análise Ergonômica do Trabalho."],
        ["Resultado inconclusivo não é ausência de risco", "A inexistência de evidência suficiente para classificar determinado risco não será automaticamente interpretada como inexistência de risco. Quando não houver evidência suficiente, o FROID poderá classificar o resultado como inconclusivo, não avaliável ou sujeito a complementação, conforme a metodologia aplicável."],
        ["AET e independência da recomendação", "Quando presentes as hipóteses previstas na NR-17 para realização de AET, o FROID poderá indicar documentalmente a necessidade de aprofundamento e disponibilizar as evidências obtidas para integração à análise subsequente, observadas as regras de proteção de dados. Salvo contratação expressa em sentido contrário, a realização da AET completa não integra o serviço FROID NR-1. A indicação de aprofundamento, AET ou metodologia complementar deverá decorrer da necessidade técnica identificada e não poderá ser condicionada à aquisição de outro produto ou serviço do FORNECEDOR."],
        ["Entregáveis", "Observado o escopo contratado, a contratante receberá: resultados agregados por unidade de avaliação e por dimensão do instrumento, observados os pisos de coorte, critérios metodológicos e regras de supressão; inventário relativo aos perigos e fatores de risco psicossociais abrangidos pelo serviço, estruturado para conter, quanto ao respectivo escopo e conforme aplicável, os elementos exigidos para integração ao inventário de riscos ocupacionais da contratante, não sendo interpretado como inventário integral de riscos físicos, químicos, biológicos, de acidentes ou demais riscos ergonômicos não avaliados; documento de critérios descrevendo gradação de severidade, gradação de probabilidade, níveis de risco, critérios de classificação, regras de tomada de decisão, tratamento de insuficiência de evidência, pisos de coorte e regras de supressão e demais parâmetros relevantes; plano de ação com as medidas a serem introduzidas, aprimoradas ou mantidas, responsáveis, cronograma, formas de acompanhamento e formas de aferição de resultados; registro das evidências e métodos aplicados no escopo avaliado, destinado a subsidiar a integração à AEP; e, nos ciclos subsequentes compatíveis, comparação de resultados de uma mesma unidade de avaliação com sua linha de base, observadas mudanças metodológicas, estruturais ou amostrais que possam afetar comparabilidade. As medidas propostas automaticamente ou sugeridas tecnicamente pelo FROID constituem recomendações até sua aprovação pela contratante. A comparação longitudinal constitui evidência de acompanhamento, não substituindo a avaliação técnica das causas, do risco residual ou da eficácia das medidas quando outros elementos forem necessários."],
        ["Avaliação e classificação dos riscos", "A avaliação utilizará critérios previamente documentados e tecnicamente justificáveis para graduação, classificação e tomada de decisão. A determinação da severidade considerará as possíveis consequências das lesões ou agravos à saúde relacionadas ao perigo avaliado, na forma dos critérios declarados no documento metodológico. A determinação da probabilidade considerará, nos limites das informações disponíveis, as exigências da atividade de trabalho, as condições de exposição, a eficácia das medidas de prevenção existentes e outros elementos tecnicamente pertinentes previstos na metodologia. Nenhum percentual, média, prevalência aparente ou escore obtido em questionário será automaticamente equiparado a um nível de risco ocupacional sem aplicação dos critérios técnicos declarados."],
        ["Obrigações da contratante", "A contratante obriga-se a: fornecer informações verdadeiras, completas e atualizadas necessárias à execução do serviço; declarar o efetivo de trabalhadores aplicável ao período de referência; manter atualizadas as informações relativas a estabelecimentos, setores e unidades de avaliação; informar alterações relevantes que possam comprometer a validade ou comparabilidade da avaliação; definir ou validar critérios de gradação e tomada de decisão de forma coerente com a metodologia geral de seu PGR; designar os responsáveis internos necessários ao GRO e ao PGR; indicar seu encarregado ou canal aplicável para assuntos de proteção de dados, quando exigível; assegurar participação, consulta e comunicação aos trabalhadores nos termos das normas aplicáveis e manter os registros correspondentes; não compelir trabalhadores a fornecer ao empregador respostas individuais destinadas ao FROID; não realizar retaliação, discriminação ou tratamento desfavorável em razão da participação, não participação ou conteúdo inferido de respostas; analisar tecnicamente os resultados recebidos; deliberar sobre as medidas de prevenção; implementar as medidas aprovadas; acompanhar seu desempenho; promover revisão do risco nas hipóteses normativamente exigidas; providenciar aprofundamento técnico ou AET quando exigível e não compreendidos no escopo contratado; integrar os documentos gerados aos demais elementos de seu PGR de modo tecnicamente coerente; e manter os documentos sob sua responsabilidade devidamente datados e assinados quando a legislação assim exigir."],
        ["Participação dos trabalhadores", "A resposta do trabalhador ao instrumento digital do FROID será voluntária. A voluntariedade da participação não significa que o tratamento realizado pelo FROID esteja baseado juridicamente em consentimento quando outra base legal for aplicável. A contratante não receberá lista individualizada de trabalhadores que recusaram, deixaram de responder ou interromperam a coleta, salvo quando determinada informação administrativa não revelar conteúdo de resposta e sua disponibilização estiver expressamente prevista, for necessária e juridicamente admissível. Adesão insuficiente poderá inviabilizar a formação de determinada unidade de avaliação ou tornar necessária a adoção de mecanismos complementares de participação e avaliação. A baixa adesão não autoriza presumir inexistência de risco."],
        ["Pisos de coorte, agregação e supressão", "Resultados não serão disponibilizados durante a evolução incremental da coleta quando sua visualização puder permitir inferência indevida sobre respostas individuais; a liberação ocorrerá após o encerramento da coleta e aplicação das regras de agregação e supressão. Nenhum recorte será publicado abaixo dos pisos de coorte definidos na metodologia aplicável. Os pisos poderão cumprir duas finalidades distintas — reduzir o risco de identificação ou reidentificação de participantes, e assegurar suficiência metodológica mínima para interpretação do resultado — e o documento metodológico deverá, sempre que aplicável, distinguir essas finalidades. Os pisos adotados constituem critérios metodológicos e de proteção definidos pelo FORNECEDOR e não serão apresentados como tamanho mínimo de coorte ou taxa de resposta expressamente prescritos pela NR-1. Quando o piso aplicável não for atingido, o resultado daquela unidade poderá ser suprimido, agregado a unidade tecnicamente compatível quando metodologicamente legítimo e previamente previsto, ou declarado insuficiente para classificação. Não será criada artificialmente conclusão sobre ausência ou baixo nível de risco em razão de insuficiência de dados."],
        ["Dados não disponibilizados à contratante", "No âmbito da coleta FROID, a contratante não receberá do FORNECEDOR, direta ou indiretamente: respostas individualizadas; associação entre identidade e resposta; escore individual; ranking individual; prontuário; diagnóstico clínico; avaliação psicológica individual; informação destinada a revelar quem respondeu determinada alternativa; nem relatório cuja granularidade permita razoavelmente reidentificar participantes. A contratante obriga-se a não solicitar, exigir, reconstruir ou tentar obter do FORNECEDOR, mediante funcionalidade, integração, exportação, solicitação de suporte, cruzamento indevido ou qualquer outro mecanismo relacionado à coleta FROID, a identidade vinculada às respostas individuais. Esta vedação não impede que a contratante receba dados individuais de trabalhador por outras fontes e finalidades juridicamente legítimas, como medicina ocupacional, comunicação espontânea, denúncia, investigação de acidente, obrigação legal, exercício regular de direitos ou ordem de autoridade competente; tais informações não se confundem com a base de respostas protegida pelo FROID e devem observar suas próprias bases legais, finalidades e regras de acesso."],
        ["Canal de apoio ao trabalhador", "Como política metodológica e de proteção adotada pelo FROID, a abertura de campanha poderá ser condicionada à existência de canal real, acessível e sigiloso de apoio ou orientação ao trabalhador, com identificação clara da forma de acesso. Essa condição constitui requisito do serviço FROID e não será apresentada como obrigação autônoma expressamente imposta pela NR-1. O canal destina-se a oferecer recurso de acolhimento ou orientação considerando que a avaliação pode revelar ou provocar relatos de sofrimento, violência, assédio ou outra circunstância que demande encaminhamento adequado. A existência de canal individual de apoio não substitui medidas destinadas a eliminar, reduzir ou controlar fatores de risco presentes na organização ou gestão do trabalho; quando a origem do risco estiver na condição de trabalho, a análise e o plano de prevenção deverão priorizar medidas adequadas sobre essa condição."],
        ["FROID Psique e serviços assistenciais", "A contratante poderá, mediante instrumento próprio, contratar o FROID Psique ou outro serviço de apoio. A contratação desse serviço não constitui requisito obrigatório para utilização do FROID NR-1, salvo se expressamente escolhido pela contratante como seu canal de apoio. Quando houver serviço clínico ou assistencial: a procura será ato do trabalhador; eventual vínculo clínico será estabelecido entre o trabalhador e o profissional ou serviço responsável pelo atendimento; a contratante não receberá prontuário, conteúdo de sessão ou diagnóstico individual em razão da utilização do FROID NR-1; o FORNECEDOR adotará segregação compatível entre a finalidade ocupacional coletiva e eventual finalidade clínica individual; e informações clínicas não serão reutilizadas para classificar individualmente o trabalhador no FROID NR-1. A recomendação de medidas de prevenção no âmbito do FROID NR-1 deverá observar a necessidade técnica identificada e não poderá favorecer serviço assistencial do próprio FORNECEDOR em detrimento de medida organizacional mais adequada."],
        ["Plano de ação e medidas de prevenção", "Os resultados da avaliação serão utilizados para identificar, conforme os critérios aplicáveis, a necessidade de introduzir, aprimorar ou manter medidas de prevenção. Recomendações geradas ou sugeridas pelo FROID não se tornam automaticamente medidas adotadas pela organização: compete à contratante, com assessoria técnica apropriada quando necessária, avaliar sua adequação, aprová-las ou justificadamente substituí-las, definir responsáveis, estabelecer cronograma, providenciar recursos e implementá-las. Quando o risco decorra da organização ou das condições do trabalho, deverão ser consideradas prioritariamente medidas que atuem sobre os fatores geradores do risco, de acordo com a hierarquia e critérios normativos aplicáveis. Medidas individuais de acolhimento, orientação ou assistência não serão tratadas como substitutas automáticas de correções organizacionais necessárias."],
        ["Acompanhamento, risco residual e eficácia", "A contratante deverá acompanhar a execução e o desempenho das medidas adotadas por meios tecnicamente apropriados. Quando houver comparabilidade metodológica, a campanha subsequente do FROID poderá constituir uma das evidências utilizadas para avaliar alteração da exposição ou eficácia das medidas, mas não constitui necessariamente o único ou suficiente meio de aferição: conforme a medida adotada e a natureza do risco, poderão ser necessários outros indicadores, inspeções, observações, entrevistas, dados organizacionais, avaliações técnicas ou mecanismos de participação dos trabalhadores. A avaliação do risco residual após a implementação de medidas constitui evento próprio do processo de gerenciamento de riscos e não deverá ser automaticamente postergada até a próxima campanha periódica quando as circunstâncias exigirem revisão anterior. O FROID não condicionará a emissão de comparação ou resultado à demonstração de melhoria; quando os dados indicarem ausência de melhora, agravamento, ineficácia aparente ou resultado inconclusivo, essa circunstância deverá ser preservada nos documentos aplicáveis."],
        ["Periodicidade e revisão", "A avaliação de riscos constitui processo contínuo. Sem prejuízo de alterações legais supervenientes, deverá observar o prazo máximo estabelecido pela NR-1, atualmente de dois anos, podendo alcançar até três anos na hipótese normativa aplicável às organizações que possuam certificação em sistema de gestão de SST. Independentemente do prazo periódico, a necessidade de revisão deverá ser analisada quando ocorrerem, entre outras hipóteses previstas na regulamentação: implementação de medidas de prevenção, para avaliação de riscos residuais; inovação ou modificação de tecnologias, ambientes, processos, condições, procedimentos ou organização do trabalho que possa criar ou alterar riscos; identificação de inadequação, insuficiência ou ineficácia das medidas; acidente ou doença relacionada ao trabalho; alteração dos requisitos legais aplicáveis; e solicitação justificada dos trabalhadores ou da CIPA, quando houver. A revisão regulatória não implica necessariamente repetição integral do mesmo questionário: a metodologia adequada à revisão será definida conforme o motivo que a originou e as evidências necessárias."],
        ["Proteção de dados pessoais: papéis e bases legais", "Quanto aos tratamentos necessários ao cumprimento das obrigações de saúde e segurança do trabalho da contratante, esta atuará como controladora, competindo-lhe as decisões relativas às finalidades do tratamento, observadas as limitações estruturais de privacidade do serviço. O FORNECEDOR atuará como operador quando realizar tratamento de dados pessoais por conta e segundo finalidades e instruções lícitas da contratante no âmbito da avaliação, e poderá atuar como controlador independente quanto aos tratamentos estritamente necessários às suas próprias finalidades legítimas e juridicamente fundamentadas, incluindo cadastro e gestão contratual, faturamento e obrigações fiscais, segurança da plataforma, prevenção e investigação de fraude, suporte, registros de auditoria, cumprimento de obrigações legais próprias e exercício regular de direitos, respeitados limitação de finalidade, necessidade e transparência. O tratamento realizado para cumprimento das obrigações regulatórias de saúde e segurança do trabalho fundamenta-se no cumprimento de obrigação legal ou regulatória pelo controlador, e não no consentimento do trabalhador, que a relação de hierarquia comprometeria. Sempre que a coleta se restringir a dados pessoais comuns, será aplicável a hipótese do art. 7º, II, da Lei nº 13.709/2018. Caso informação coletada seja juridicamente caracterizada como dado pessoal sensível e seu tratamento seja indispensável à finalidade regulatória, aplica-se também o art. 11, II, alínea a, sem prejuízo das demais hipóteses legais cabíveis. A distinção importa porque é o conteúdo real das perguntas, e não o rótulo contratual, que determina a natureza dos dados tratados. A participação voluntária do trabalhador no questionário não implica que consentimento seja necessariamente a base legal do tratamento, e as partes não utilizarão consentimento como fundamento meramente formal para contornar hipótese legal mais adequada à finalidade regulatória."],
        ["Minimização, dados sensíveis e texto livre", "O FROID deverá limitar a coleta aos dados adequados, pertinentes e necessários às finalidades declaradas. Ainda que o instrumento não tenha finalidade clínica, o trabalhador poderá eventualmente inserir informação capaz de revelar dado pessoal sensível; a ocorrência incidental não converte o serviço em avaliação clínica, mas deverá receber proteção compatível com a natureza do dado efetivamente tratado. Sempre que houver campo de texto livre, o sistema poderá orientar o trabalhador a evitar inclusão desnecessária de nomes, diagnósticos ou informações individualizantes de terceiros."],
        ["Segurança da informação", "O FORNECEDOR adotará medidas técnicas e administrativas compatíveis com a natureza dos dados, o contexto do tratamento e os riscos envolvidos, incluindo, conforme tecnicamente aplicável: segregação lógica entre clientes; controle de acesso baseado em necessidade e privilégio mínimo; autenticação; criptografia em trânsito e, quando apropriado, em repouso; registro de eventos relevantes; mecanismos de backup e recuperação; controle de ambiente de produção; proteção contra acesso não autorizado; e procedimentos de gestão de vulnerabilidades e incidentes. Eventual acesso técnico do FORNECEDOR a dados não disponibilizados à contratante deverá ocorrer apenas quando necessário para segurança, manutenção, suporte, recuperação, investigação de incidente, cumprimento de obrigação legal ou outra finalidade legítima, mediante controles de acesso compatíveis, dever de confidencialidade e registro quando tecnicamente aplicável. A proteção estrutural das respostas contra acesso pela contratante não será interpretada como declaração de inexistência física ou lógica de qualquer possibilidade técnica de acesso por pessoal estritamente autorizado do FORNECEDOR nas situações excepcionais previstas nesta cláusula."],
        ["Incidentes de segurança", "O FORNECEDOR comunicará à contratante, sem demora indevida após tomar conhecimento e realizar avaliação inicial suficiente, incidente de segurança envolvendo dados pessoais tratados como operador que possa exigir providência do controlador. A comunicação deverá conter, na medida em que as informações estiverem disponíveis, a natureza do incidente, as categorias de dados afetadas, os titulares potencialmente envolvidos, os riscos identificados, as medidas adotadas ou planejadas e as informações necessárias à avaliação das obrigações legais da contratante. As comunicações à ANPD, aos titulares ou a outras autoridades serão realizadas pelo agente legalmente responsável, com cooperação razoável da outra parte."],
        ["Suboperadores e terceiros", "O FORNECEDOR poderá utilizar terceiros necessários à infraestrutura e execução do serviço, inclusive provedores de hospedagem, comunicação, segurança, processamento e suporte, desde que sejam submetidos a obrigações compatíveis de confidencialidade e proteção de dados, recebam apenas os dados necessários à sua função, sejam adotadas salvaguardas legalmente exigidas em eventual transferência internacional e permaneça o FORNECEDOR responsável pelas obrigações que a lei lhe atribua como operador ou controlador."],
        ["Retenção e guarda", "O histórico das atualizações do inventário de riscos produzido no âmbito do serviço deverá ser preservado pelo prazo mínimo legal aplicável, atualmente de vinte anos, sem prejuízo de prazo superior previsto em norma específica. A obrigação de conservação do histórico do inventário não será automaticamente interpretada como obrigação de conservar por igual período toda resposta bruta ou dado intermediário utilizado para produzi-lo. Dados brutos identificáveis ou pseudonimizados serão mantidos somente pelo prazo necessário às finalidades legítimas que justifiquem sua retenção, considerando elaboração e validação dos resultados, segurança, rastreabilidade necessária, cumprimento de obrigação legal, exercício regular de direitos e demais hipóteses juridicamente justificáveis. Dados efetivamente anonimizados, quando não puderem ser razoavelmente associados a pessoa natural mediante meios próprios ou esforços razoáveis, poderão ser utilizados e preservados nos limites permitidos pela legislação e pelas obrigações de confidencialidade. Quando determinado documento estiver sujeito a prazo obrigatório de guarda, o sistema poderá impedir sua exclusão durante esse período, recaindo a restrição apenas sobre os registros cuja conservação possua fundamento jurídico, técnico ou probatório legítimo."],
        ["Disponibilidade dos documentos do PGR", "A contratante será responsável por disponibilizar os documentos integrantes do PGR aos sujeitos que tenham direito de acesso nos termos da legislação aplicável, incluindo trabalhadores interessados, representantes sindicais e Inspeção do Trabalho quando pertinente. O dever de disponibilização dos documentos do PGR não implica disponibilização de respostas brutas individuais, bancos protegidos, credenciais, chaves, registros técnicos internos ou informação cuja entrega possa comprometer a proteção dos participantes, salvo obrigação legal específica ou determinação válida da autoridade competente."],
        ["Rastreabilidade e integridade da evidência", "Sempre que tecnicamente viável, os documentos gerados deverão permitir identificar o período da coleta, o estabelecimento e a unidade de avaliação, a versão do instrumento, a versão relevante da metodologia, os critérios de avaliação, os pisos de coorte, os parâmetros aplicáveis, a data de geração e as alterações ou revisões relevantes. Alterações metodológicas futuras não deverão modificar retroativamente o conteúdo histórico já consolidado de ciclos anteriores; quando documento anterior for corrigido por erro material ou técnico, deverá haver registro suficiente da revisão. O objetivo da rastreabilidade é permitir que, diante de fiscalização, auditoria, perícia ou controvérsia futura, seja possível compreender razoavelmente o que foi avaliado, com qual método, quais critérios foram empregados, quais resultados foram obtidos, quais decisões foram tomadas pela contratante, quais medidas foram registradas e quais revisões posteriores ocorreram."],
        ["eSocial e outros sistemas", "O FROID NR-1 não gera eventos de eSocial, salvo se funcionalidade específica vier a ser expressamente contratada. A contratante permanece responsável pelas informações que transmitir aos sistemas oficiais e pela coerência entre essas informações, seu PGR e os demais documentos de SST."],
        ["Propriedade intelectual", "Permanecem de titularidade do FORNECEDOR, na extensão em que lhe pertençam: software, código-fonte e código objeto, marca FROID, instrumentos, textos padronizados, metodologia, taxonomias, modelos, interfaces, estruturas, algoritmos, parâmetros gerais, documentação técnica preexistente, know-how e segredos comerciais; a contratação não transfere à contratante a titularidade desses elementos. Dados cadastrais, informações organizacionais fornecidas pela contratante e resultados específicos relativos à sua organização permanecem vinculados à contratante, observadas as regras legais aplicáveis aos dados pessoais dos trabalhadores. A contratante terá direito permanente de armazenar, reproduzir, apresentar e utilizar os documentos específicos produzidos para seu PGR, incluindo inventários, planos de ação, registros, critérios aplicáveis ao ciclo e evidências exportáveis, inclusive para gestão interna, auditoria, fiscalização, perícia, processo administrativo, processo judicial e exercício regular de direitos. Esse direito de uso não transfere a titularidade sobre metodologia, software, templates estruturais, algoritmos ou outros componentes intelectuais preexistentes incorporados aos documentos."],
        ["Condições comerciais", "O preço será o constante da proposta comercial aceita pela contratante e poderá considerar, entre outros fatores, o efetivo declarado, a quantidade de estabelecimentos, as unidades de avaliação, serviços adicionais, a periodicidade e o escopo contratado. Para fins comerciais, estabelecimento será considerado conforme o critério definido na proposta e na metodologia do serviço; departamentos ou áreas localizados no mesmo endereço poderão constituir setores ou unidades de avaliação sem necessariamente constituir estabelecimento comercial adicional, conforme as condições da proposta. Alteração relevante de efetivo, estabelecimentos, estrutura organizacional ou escopo poderá ocasionar revisão do preço para ciclo futuro ou serviço adicional, mediante nova proposta ou ajuste contratual."],
        ["Limites do serviço", "Salvo contratação expressa, o FROID NR-1 não substitui assessoria jurídica; não presta diagnóstico clínico; não realiza exame médico ocupacional; não substitui o PCMSO; não realiza automaticamente AET completa; não avalia riscos ocupacionais fora do escopo definido; não substitui decisão empresarial sobre medidas de prevenção; não garante que a simples contratação do serviço seja suficiente para cumprimento integral de todas as obrigações de SST da contratante; não garante inexistência de risco; não constitui certificação oficial de conformidade; e não impede fiscalização, autuação, demanda trabalhista ou divergência técnica futura. A função do FROID é produzir e organizar evidências tecnicamente estruturadas para apoiar o cumprimento das obrigações incluídas no seu escopo."],
        ["Dever de cooperação e correção", "As partes deverão cooperar de boa-fé para correção de inconsistências identificadas. Erro técnico imputável ao FORNECEDOR deverá ser corrigido, preservando-se a rastreabilidade da alteração quando o erro já tiver alcançado documento consolidado. Erro decorrente de informação fornecida pela contratante será corrigido quando tecnicamente possível, podendo gerar custo adicional quando exigir reprocessamento relevante não decorrente de falha do FORNECEDOR."],
        ["Confidencialidade", "Cada parte deverá manter sob sigilo informações confidenciais da outra a que tiver acesso em razão do contrato, utilizando-as apenas para execução das finalidades legítimas relacionadas à relação contratual. Não serão consideradas confidenciais informações que sejam comprovadamente públicas sem violação deste contrato, que já fossem legitimamente conhecidas pela parte receptora, que sejam recebidas legitimamente de terceiro sem obrigação de sigilo ou que devam ser divulgadas por lei ou ordem válida de autoridade competente; quando juridicamente possível, a parte obrigada à divulgação comunicará previamente a outra."],
        ["Vigência, encerramento e exportação", "A vigência será definida na proposta comercial ou no aceite eletrônico correspondente. Encerrado o contrato, a contratante poderá exportar os documentos gerados durante a vigência conforme as funcionalidades previstas; o FORNECEDOR poderá conservar documentos e registros cuja manutenção seja necessária ao cumprimento de obrigação legal, regulatória, segurança, defesa de direitos ou outra finalidade legítima; dados que não possuam fundamento para retenção serão eliminados ou anonimizados de acordo com a política aplicável e os prazos técnicos necessários; e o encerramento não produzirá apagamento de registros submetidos a prazo legal obrigatório de guarda. A cessação do contrato não transfere ao FORNECEDOR a responsabilidade pela continuidade do GRO, do PGR ou das medidas de prevenção da contratante."],
        ["Alterações regulatórias e metodológicas", "O FORNECEDOR poderá adaptar o serviço quando houver modificação de legislação, Norma Regulamentadora, interpretação oficial ou requisito técnico que afete o escopo; mudança que implique alteração substancial de preço ou de serviço contratado será comunicada e, quando necessário, submetida a nova contratação. A metodologia poderá ser aperfeiçoada ao longo do tempo, preservando-se a identificação da versão utilizada em cada ciclo, e mudanças metodológicas que afetem comparabilidade histórica deverão ser informadas ou evidenciadas nos resultados correspondentes."],
        ["Responsabilidade e alocação de riscos", "A contratante responde pela veracidade das informações sob seu controle, pela estruturação e manutenção de seu GRO e PGR, pela integração dos resultados aos demais riscos, pelas decisões relativas às medidas, pela implementação das medidas e pelo cumprimento das obrigações empresariais que não tenham sido expressamente assumidas pelo FORNECEDOR. O FORNECEDOR responde pela adequada prestação do serviço contratado e pelos atos ou omissões que a legislação lhe atribua. Nenhuma disposição deste contrato deverá ser interpretada como exclusão de responsabilidade que, por lei, seja inderrogavelmente atribuída a qualquer das partes. O FORNECEDOR não será responsável por decisão da contratante contrária às evidências apresentadas, não implementação das medidas, uso do documento fora de sua finalidade, manipulação externa dos resultados, alteração não autorizada dos documentos, omissão de informação relevante pela contratante ou utilização de método complementar por terceiro cuja execução não esteja sob sua responsabilidade."],
        ["Evidência, fiscalização e processos", "Os documentos gerados pelo FROID poderão ser utilizados pela contratante como elementos de evidência de seu processo de gerenciamento de riscos perante auditoria, fiscalização, processo administrativo ou judicial. A existência desses documentos não representa garantia antecipada de aceitação de suas conclusões por autoridade, perito ou terceiro, cuja apreciação observará a legislação aplicável, a situação concreta e o conjunto de evidências disponível. O FORNECEDOR deverá preservar, nos limites de sua obrigação de guarda, os elementos necessários à compreensão da metodologia e da versão aplicadas ao ciclo, sem obrigação de revelar código-fonte, segredo industrial ou informação de outro cliente, salvo determinação legal válida."],
        ["Interpretação conforme a finalidade regulatória", "Este contrato deverá ser interpretado de modo a preservar a responsabilidade legal da organização pelo GRO e pelo PGR; assegurar a independência técnica da avaliação; evitar diagnóstico individual indevido; proteger a confidencialidade dos trabalhadores; favorecer a identificação e prevenção efetivas dos riscos; permitir aprofundamento técnico quando as evidências iniciais forem insuficientes; evitar que ausência de dado seja confundida com ausência de risco; e preservar a rastreabilidade das decisões e evidências do processo."],
        ["Disposições gerais", "A invalidade ou inexigibilidade de uma disposição não afetará as demais, salvo quando a disposição invalidada for essencial à estrutura da contratação. A tolerância de qualquer das partes quanto ao descumprimento de obrigação não implicará renúncia, novação ou alteração contratual. Comunicações relacionadas ao contrato poderão ocorrer pelos meios eletrônicos cadastrados pelas partes, sem prejuízo de mecanismo específico previsto na plataforma ou proposta. Alterações substanciais deste instrumento deverão ser realizadas por mecanismo que permita comprovar seu conteúdo e aceite. Aplica-se a legislação da República Federativa do Brasil, especialmente as normas de saúde e segurança do trabalho, proteção de dados, direito civil e demais normas pertinentes. Fica eleito o foro definido na proposta comercial ou, na ausência de estipulação específica, o foro legalmente competente, ressalvadas competências inderrogáveis e regras de proteção eventualmente aplicáveis ao caso concreto."],
        ["Declarações finais", "Ao contratar o FROID NR-1, a contratante declara estar ciente de que o gerenciamento de riscos ocupacionais é processo contínuo; que fatores de risco psicossociais relacionados ao trabalho devem ser analisados como condições de trabalho, e não confundidos com diagnóstico psicológico individual; que questionário constitui ferramenta de avaliação, e não metodologia obrigatória ou universalmente suficiente; que situações específicas poderão exigir complementação metodológica ou AET; que ausência de resultado em razão de insuficiência de participação ou proteção de coorte não equivale a ausência de risco; que a prevenção deve orientar-se pelas condições concretas identificadas; que o acompanhamento das medidas não se limita à repetição periódica do questionário; que a responsabilidade legal da contratante pelo GRO e pelo PGR permanece íntegra; que essa responsabilidade não exclui a responsabilidade própria do FORNECEDOR pela adequada prestação do serviço contratado; e que os resultados agregados e documentos gerados deverão ser interpretados no contexto das demais informações do sistema de SST da organização. As condições comerciais específicas, número de trabalhadores, estabelecimentos, vigência, preço, forma de pagamento e eventuais serviços adicionais são aquelas constantes da proposta comercial aceita pela contratante."],
    ],
}


def public_legal_catalog() -> dict[str, Any]:
    supplier = _supplier()
    supplier_identity = (
        f"{supplier['name']}, CPF {supplier['tax_id']}, com endereço em "
        f"{supplier['address']} e contato {supplier['contact_email']}"
        if supplier["configured"] else "fornecedor do FROID (configuração jurídica pendente)"
    )
    documents: dict[str, Any] = {}
    for key, template in DOCUMENT_TEMPLATES.items():
        sections = [
            {
                "heading": heading,
                "body": body.format(
                    supplier_name=supplier["name"] or "fornecedor do FROID",
                    supplier_identity=supplier_identity,
                ),
            }
            for heading, body in template["sections"]
        ]
        rendered = {
            "key": key,
            "version": LEGAL_DOCUMENT_VERSION,
            "title": template["title"],
            "audiences": template["audiences"],
            "sections": sections,
        }
        canonical = json.dumps(rendered, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        rendered["sha256"] = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
        documents[key] = rendered
    return {
        "version": LEGAL_DOCUMENT_VERSION,
        "supplier": supplier,
        "documents": documents,
    }


def required_document_keys(account_type: str) -> list[str]:
    # A empresa contratante do NR-1 nao assina contrato de profissional nem de
    # clinica: ela nao presta servico clinico e nao trata prontuario. Os dois
    # contratos do catalogo tem audiencia declarada ("professional" e
    # "organization"), e nenhuma delas e o empregador. Fazer o empregador
    # declarar aceite de um contrato profissional produziria registro juridico
    # falso — pior que nao coletar. Termos e privacidade valem para qualquer um
    # que use a plataforma, e esses continuam.
    #
    # O contrato empresarial de avaliacao NR-1 existe desde 22/08/2026 e diz, no
    # objeto, o que os outros dois nao podiam dizer: que a avaliacao olha para a
    # condicao de trabalho e nunca para a pessoa, e que a responsabilidade pelo
    # GRO continua sendo da empresa.
    if account_type == "nr1_company":
        return ["terms", "privacy", "nr1_company_contract"]
    contract = "organization_contract" if account_type == "organization" else "professional_contract"
    return ["terms", "privacy", contract]
